
spring:
  application:
    name: CustomerService

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

  data:
    mongodb:
      uri: mongodb://localhost:27017/customer
      username: customer
      password: customerpassword
      authentication-database: customer

server:
  port: 8080
