spring:
  application:
    name: ORDERSCOMMANDSERVICE

  data:
    mongodb:
      uri: mongodb://localhost:27017/orders
      username: orders
      password: secure-password
      authentication-database: orders

    kafka:
      order-topic: orders-events
      bootstrap-servers: localhost:9092
      producer:
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.springframework.kafka.support.serializer.JsonSerializer


server:
  port: 8081