spring:
  application:
    name: Gateway
  cloud:
    gateway:
      routes:
        - id: customerModule
          uri: http://localhost:8080/
          predicates:
            - Path=/customers/**
        - id: ordercommandModule
          uri: http://localhost:8081/
          predicates:
            - Path=/orders/**
        - id: orderqueryModule
          uri: http://localhost:8082/
          predicates:
            - Path=/order/**
        - id: paymentModule
          uri: http://localhost:8083/
          predicates:
            - Path=/payments/**
        - id: productModule
          uri: http://localhost:8084/
          predicates:
            - Path=/products/**

server:
  port: 8090

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
