spring:
  application:
    name: PAYMENTSERVICE

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

  data:
    mongodb:
      uri: mongodb://localhost:27017/payments
      username: payment
      password: securepassword
      authentication-database: payment

server:
  port: 8083